"""Canonical KAHLE locations; runtime copies are generated by build_tools.py.

A new or renamed location is edited in this table only. Afterwards run
``python stack/open-webui-tools/build_tools.py``; it updates the harness copy,
the toolcall guard block and the tool bundles. ``--check`` reports every copy
that was not rebuilt.
"""

from __future__ import annotations


# (Kurzname, vollständiger Name, interne Kürzel in Großbuchstaben)
KAHLE_LOCATION_TABLE = (
    ("Hannover", "Hannover", ("HAN",)),
    ("Wunstorf", "Wunstorf", ("WUN",)),
    ("Wedemark", "Wedemark", ("WED",)),
    ("Walsrode", "Walsrode", ("WAL",)),
    ("Neustadt", "Neustadt am Rübenberge", ("NEU",)),
    ("Nienburg", "Nienburg", ("NIE",)),
    ("Stadthagen", "Stadthagen", ("SHG",)),
)
KAHLE_LOCATIONS = tuple(name for name, _, _ in KAHLE_LOCATION_TABLE)
KAHLE_LOCATION_FULL_NAMES = tuple(full_name for _, full_name, _ in KAHLE_LOCATION_TABLE)
KAHLE_LOCATION_CODES = tuple(
    (code, full_name) for _, full_name, codes in KAHLE_LOCATION_TABLE for code in codes
)
